### PR TITLE
support for TinyMCE > 2.0

### PR DESCRIPTION
**Pull request by fskarder**
Updated this project with TinyMCE 2.xx support for a new project. Might be useful for others as well.

### CODE REVIEW

**Review by MattisOlsson — APPROVED** [review]
Thanks for your contribution!

**Comment by tomludd** [comment]
When will this be available on episerver nuget? @MattisOlsson 
Last update on Episerver nuget is Sept 2018. 
https://nuget.episerver.com/package/?id=Geta.EPi.Imageshop

**Comment by murela** [comment]
@fskarder or @MattisOlsson it seems the changes in this pull request is'nt published to the Episerver Nuget feed. It would me much appreciated if you could do that :)

**Comment by MattisOlsson** [comment]
Hi, sorry for the delay guys. Version 2.3.0 is now uploaded and will be available as soon as Episerver approve it.

**Pull request merged**
